# .streamlit/secrets.toml
[general]
OPENAI_API_KEY = "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"
